FROM python:alpine3.7

ARG GCP_PROJECT_ID
ARG GCP_TOPIC_NAME
ARG GCP_SUBSCRIPTION_NAME

ENV GCP_PROJECT_ID=$GCP_PROJECT_ID
ENV GCP_TOPIC_NAME=$GCP_TOPIC_NAME
ENV GCP_SUBSCRIPTION_NAME=$GCP_SUBSCRIPTION_NAME

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000
CMD python ./index.py